# Generated by Django 4.1.7 on 2023-07-27 01:35

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('documento', models.TextField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=30)),
                ('apellido', models.TextField(max_length=30)),
                ('correo', models.TextField(max_length=30)),
                ('celular', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LineasCredito',
            fields=[
                ('codigo', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.TextField(max_length=30)),
                ('montomaximo', models.PositiveBigIntegerField(verbose_name='Monto maximo')),
                ('plazomaximo', models.PositiveSmallIntegerField(verbose_name='Plazo maximo')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, default='dos.png', null=True, upload_to='user_images/')),
                ('documento', models.TextField(max_length=30, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.PositiveBigIntegerField(verbose_name='Total credito')),
                ('plazo', models.PositiveSmallIntegerField(choices=[(6, 6), (12, 12), (18, 18), (4, 24)], default=6, verbose_name='Plazo')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appbanco.lineascredito')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appbanco.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
