# Generated by Django 4.1.7 on 2023-08-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appbanco', '0003_alter_cliente_documento_alter_user_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[[0, 'Cliente'], [1, 'Empleado']], max_length=100),
        ),
    ]
